application: ben-shope
version: dev
runtime: python27
api_version: 1
threadsafe: true

skip_files:
- ^README\..*
- \.gitignore
- ^\.git/.*
- ^fabfile\.py

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /img
  static_dir: img
- url: /
  static_files: html/index.html
  upload: html/index.html
- url: /
  static_dir: html