application: angular-engine
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /login
  script: main.app
- url: /logout
  script: main.app
- url: /contact
  script: main.app
- url: /database
  script: main.app
- url: /static
  static_dir: static
- url: .*
  static_files: static/index.html
  upload: static/index.html

libraries:
- name: webapp2
  version: latest