application: ben-shope
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: app/img/favicon.ico
  upload: app/img/favicon\.ico
- url: /app
  static_dir: app
- url: /html
  static_dir: app/html
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest